test: hello

diff --git a/.github/workflows/commit.yaml b/.github/workflows/commit.yaml
--- a/.github/workflows/commit.yaml
+++ b/.github/workflows/commit.yaml
@@ -23,19 +23,16 @@ jobs:
         INVALID_COMMIT_FORMAT_REGEX="^(feat|fix|chore|docs|style|refactor|perf|test|build|ci|revert)(\(.+\))?:\ .+"
         commits_url="${{ github.event.pull_request._links.commits.href }}"
         commits=$(curl -sSL $commits_url)
-        echo "$commits"
-        commit_shas=$(echo "$commits" | jq -r '.[] | .sha')
-        for sha in $commit_shas; do
-          echo "$sha"
-          message=$(git log --format="%H %s" -n 1 $sha)
-          echo "$message"
-          # Check if it's a merge commit
-          if [[ $message =~ .*Merge\ .+\ into\ .+$ ]]; then
-            continue
-          fi
+        messages=$(echo "$commits" | jq -r '.[] | .commit.message')
+        for msg in $messages; do
+          echo "$msg"
+          # # Check if it's a merge commit
+          # if [[ $message =~ .*Merge\ .+\ into\ .+$ ]]; then
+          #   continue
+          # fi
 
-          if [[ ! $message =~ $INVALID_COMMIT_FORMAT_REGEX ]]; then
-            echo "Invalid commit message format: $message"
-            exit 1
-          fi
+          # if [[ ! $message =~ $INVALID_COMMIT_FORMAT_REGEX ]]; then
+          #   echo "Invalid commit message format: $message"
+          #   exit 1
+          # fi
         done
